server:
  error:
    include-message: always
    include-stacktrace: always
    include-binding-errors: always
  port: 8080


spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: prajvaltheking@gmail.com
    password: tzseattdglngndjs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://localhost:3306/user-registration
    username: root
    password: EasyPass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create




